version: '3.5'

services:
  dscience:
    image: zoro1666/dscience
    ports:
      - 8888:8888
      - 6006:6006
      - 7007:7007
    volumes:
      - .:/models  # map this current directory with /usr/src/api in the docker container
    command: jupyter-notebook --allow-root
